spring:
  datasource:
    username: root
    password: root
  redis:
    password: root

logging:
  config: classpath:log4j2/log4j2-spring-dev.xml

file:
  uploadFolder: C://Users//Arslinth//Pictures//spriingImg//

# 第三方登录
justAuth:
  callbackUrl: http://localhost:8100/manage/callback